name: flutter_trading_app
description: A Flutter app displaying trading instruments with real-time price updates.

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  dio: ^5.3.2
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.9.0
  equatable: ^2.0.5
  pull_to_refresh: ^2.0.0
  flutter_easyloading: ^3.0.5
  auto_size_text: ^3.0.0
  fluro: ^2.0.5
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.0
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  bloc_test: ^9.1.3

flutter:
  uses-material-design: true

  #assets:
   # - assets/images/